version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /cmake/tribits/doc/sphinx
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/exodus
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/seacas
    schedule:
      interval: daily
